spring:
  application:
    name: APiGatewayService
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      server:
        webflux:
          routes:
            - id: USERSERVICEJWT
              uri: lb:http://UserServiceJWT
              predicates:
                - Path=/user/**,/admin/**,/auth/google/**
#            - id: ArticleService
#              uri: lb:http://ArticleService
#              predicates:
#                - Path=

server:
  port: 8085

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
